[package]
name = "persistence"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
rusqlite = { workspace = true }
refinery = { workspace = true }
game_core = { workspace = true }
resources = { workspace = true }
states = { workspace = true }
logging = { workspace = true }
crossbeam-channel = { workspace = true }

[lints]
workspace = true
