use bevy::prelude::*;

use game_core::prelude::{Moment, MomentKind, MomentOf};
use logging::prelude::*;

use crate::{
    load::{LoadContext, LoadResult},
    rusqlite,
    save::{SaveRunner, SaveWriter},
};

// ============================================================================
// Generic moment persistence helpers
//
// Written once, called from each domain's `_internal` crate. Parameterized by
// `M: MomentKind` — the `KIND` const selects the domain's rows from the shared
// `moments` table.
// ============================================================================

/// Save all moments of kind `M` to the `moments` table. Registered via
/// `register_moment_persistence`. Scenario saves reset `fired_count` to 0;
/// quick saves preserve it.
#[log_tags(Tag::GameSave)]
pub fn save_moments<M: MomentKind>(
    save_runner: Res<SaveRunner>,
    mut save: SaveWriter,
    moments: Query<(Entity, &Moment, &MomentOf, &M)>,
) {
    if moments.is_empty() { return; }
    #[debug_dev("Saving {} '{}' moments", rows.len(), M::KIND)]
    let rows: Vec<(u32, u32, &'static str, u32)> = moments
        .iter()
        .map(|(entity, moment, parent, _marker)| {
            let id = entity.index_u32();
            let parent_id = parent.0.index_u32();
            let fired_count = if save_runner.save_as_scenario { 0 } else { moment.fired_count };
            (id, parent_id, M::KIND, fired_count)
        })
        .collect();
    save.submit(move |ctx| {
        for (id, parent_id, kind, fired_count) in rows {
            ctx.register_entity(id)?;
            ctx.register_entity(parent_id)?;
            ctx.tx.execute(
                "INSERT OR REPLACE INTO moments (id, parent_id, kind, fired_count) VALUES (?1, ?2, ?3, ?4)",
                rusqlite::params![id, parent_id, kind, fired_count],
            )?;
        }
        Ok(())
    });
}

/// Load all moments of kind `M` from the `moments` table and restore them via
/// `ctx.insert`. Registered via `register_moment_persistence`.
pub fn load_moments<M: MomentKind>(ctx: &mut LoadContext) -> LoadResult {
    // `M::KIND` is an identifier generated by the `MomentKind` derive, so inlining it is safe.
    let query = format!("SELECT id, parent_id, fired_count FROM moments WHERE kind = '{}'", M::KIND);
    ctx.for_each_entity(&query, |ctx, _, entity, row| {
        let old_parent_id: u32 = row.get(1)?;
        let fired_count: u32 = row.get(2)?;
        let parent = ctx.entity(old_parent_id)?;
        ctx.insert(entity, (
            Moment { fired_count },
            MomentOf(parent),
            M::default(),
        ));
        Ok(())
    })
}
