[package]
name = "grids_internal"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
game_core = { workspace = true }
grids = { workspace = true }
buildings = { workspace = true }
alteration = { workspace = true }
persistence = { workspace = true }
states = { workspace = true }
almanach = { workspace = true }
viewport = { workspace = true }

[lints]
workspace = true
