[package]
name = "shards_internal"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
game_core = { workspace = true }
states = { workspace = true }
persistence = { workspace = true }
logging = { workspace = true }
shards = { workspace = true }
almanach = { workspace = true }
resources = { workspace = true }
