//! Force field entities generated by TowerField buildings.
//!
//! Each active TowerField spawns a `ForceField` entity (separate from the tower)
//! when it has power and is not disabled. The field animates via `ForceFieldState`
//! (Growing → Shrinking) and despawns when progress reaches 0.0.
//!
//! `ForceFieldGrid` (lib-grid) tracks per-cell Voronoi ownership across the map.
//! `field_tracking_system` fires `ForceFieldEntered` / `ForceFieldExited` on boundary crossings.

use lib_grid::grids::force_fields::ForceFieldGrid;

use crate::prelude::*;

const STARTUP_SPEED: f32 = 0.8; // progress units per second (0→1 in ~1.25s)

pub struct ForceFieldPlugin;
impl Plugin for ForceFieldPlugin {
    fn build(&self, app: &mut App) {
        app
            .add_observer(BuilderForceField::on_add)
            .add_systems(PreUpdate,
                recompute_force_field_grid_system.run_if(resource_exists::<ForceFieldGrid>),
            )
            .add_systems(Update, (
                    ForceField::progress_system,
                    field_tracking_system,
                ).run_if(in_state(GameState::Running)
            ))
            ;
    }
}

// ── Relationships ──────────────────────────────────────────────────────────────────────

#[derive(Component)]
#[relationship(relationship_target = GeneratedForceField)]
pub struct ForceFieldGeneratedBy(pub Entity);

#[derive(Component)]
#[relationship_target(relationship = ForceFieldGeneratedBy)]
pub struct GeneratedForceField(Entity);

/// Tracks which `ForceField` entity currently owns this entity's grid cell.
///
/// Managed exclusively by `field_tracking_system` in the game crate.
/// Added at spawn to any entity that can be affected by force fields (wisps, drones, etc.).
#[derive(Component, Default)]
pub struct FieldAffected {
    pub current_field: Option<Entity>,
}

// ── ForceFieldState ────────────────────────────────────────────────────────────────────

#[derive(Component)]
#[component(immutable)]
pub enum ForceFieldState {
    Growing,
    Shrinking,
}

// ── ForceField Events ────────────────────────────────────────────────────────────────────

/// Triggered on a `ForceField` entity when a tracked entity enters its Voronoi cell.
/// `exited_field` is set when the entity crossed directly from another field (seam crossing),
/// and `None` when entering from outside all fields.
#[derive(EntityEvent, Clone, Copy)]
pub struct ForceFieldEntered {
    #[event_target]
    pub field: Entity,
    pub target: Entity,
    pub exited_field: Option<Entity>,
}

/// Triggered on a `ForceField` entity when a tracked entity leaves its Voronoi cell.
#[derive(EntityEvent, Clone, Copy)]
pub struct ForceFieldExited {
    #[event_target]
    pub field: Entity,
    pub target: Entity,
}

// ── ForceField ─────────────────────────────────────────────────────────────────────────

#[derive(Component)]
#[require(MapBound)]
pub struct ForceField {
    /// Field radius in world units.
    pub radius: f32,
    /// Animated progress 0.0 (gone) → 1.0 (full). Drives both visual size and Voronoi weight.
    pub progress: f32,
    /// Random per-field offset added to global time in the noise function.
    pub visual_noise_offset: f32,
}
impl ForceField {
    pub fn new(radius: f32) -> Self {
        let mut rng = nanorand::tls_rng();
        Self {
            radius,
            progress: 0.0,
            visual_noise_offset: nanorand::Rng::generate::<f32>(&mut rng) * 100.0,
        }
    }

    fn progress_system(
        mut commands: Commands,
        time: Res<Time>,
        mut fields: Query<(Entity, &mut ForceField, &ForceFieldState)>,
    ) {
        for (entity, mut field, state) in fields.iter_mut() {
            match state {
                ForceFieldState::Growing => {
                    if field.progress < 1.0 {
                        field.progress = (field.progress + STARTUP_SPEED * time.delta_secs()).min(1.0);
                    }
                }
                ForceFieldState::Shrinking => {
                    if field.progress > 0.0 {
                        field.progress = (field.progress - STARTUP_SPEED * time.delta_secs()).max(0.0);
                        if field.progress <= 0.0 {
                            commands.entity(entity).despawn();
                        }
                    }
                }
            }
        }
    }
}

// ── BuilderForceField ──────────────────────────────────────────────────────────────────

#[derive(Component)]
pub struct BuilderForceField {
    pub radius: f32,
    pub tower_entity: Entity,
    pub world_position: Vec3,
}
impl BuilderForceField {
    pub fn new(radius: f32, tower_entity: Entity, world_position: Vec3) -> Self {
        Self { radius, tower_entity, world_position }
    }

    pub fn on_add(
        trigger: On<Add, BuilderForceField>,
        mut commands: Commands,
        builders: Query<&BuilderForceField>,
    ) {
        let entity = trigger.entity;
        let Ok(builder) = builders.get(entity) else { return; };
        let (radius, tower_entity, world_position) = (builder.radius, builder.tower_entity, builder.world_position);

        commands.entity(entity)
            .remove::<BuilderForceField>()
            .insert((
                ForceField::new(radius),
                ForceFieldState::Growing,
                ForceFieldGeneratedBy(tower_entity),
                Transform::from_translation(world_position),
            ));
    }
}

// ── Grid recompute ─────────────────────────────────────────────────────────────────────

fn recompute_force_field_grid_system(
    mut grid: ResMut<ForceFieldGrid>,
    fields: Query<(Entity, &ForceField, &Transform)>,
    // Checked only for emptiness — tells us if any ForceField data changed this frame.
    // ForceField::progress animates every frame, so this fires on every frame with active fields.
    changed_fields: Query<(), Changed<ForceField>>,
    removed_fields: RemovedComponents<ForceField>,
) {
    if changed_fields.is_empty() && removed_fields.is_empty() { return; }

    // Recompute the entire grid as a weighted Voronoi diagram.
    // Each cell is assigned to whichever field is "deepest" inside it
    // (smallest normalized distance = actual_dist / effective_radius).
    for y in 0..grid.height {
        for x in 0..grid.width {
            let cell_center = Vec2::new((x as f32 + 0.5) * CELL_SIZE, (y as f32 + 0.5) * CELL_SIZE);
            let idx = grid.index(GridCoords { x, y });
            grid.grid[idx] = find_owning_field(cell_center, &fields);
        }
    }
    grid.version = grid.version.wrapping_add(1);
}

/// Returns the `ForceField` entity that owns `pos` via weighted Voronoi, or `None` if
/// `pos` is not covered by any field.
///
/// "Ownership" uses normalized distance (`actual_distance / effective_radius`) so that
/// larger fields don't automatically swallow smaller ones — a small field still wins
/// for points deep within it. A normalized distance of 1.0 means exactly on the edge;
/// anything above 1.0 is outside and does not qualify.
fn find_owning_field(pos: Vec2, fields: &Query<(Entity, &ForceField, &Transform)>) -> Option<Entity> {
    fields.iter()
        .filter_map(|(entity, field, transform)| {
            let effective_radius = field.radius * field.progress;
            // Fields at progress ≈ 0 (fully collapsed) don't own any cells.
            if effective_radius < 0.001 { return None; }

            let normalized_distance = pos.distance(transform.translation.xy()) / effective_radius;
            // Only consider fields that actually cover this point (inside or on the edge).
            if normalized_distance <= 1.0 { Some((entity, normalized_distance)) } else { None }
        })
        // The field with the smallest normalized distance is the deepest/dominant owner.
        .min_by(|(_, distance_a), (_, distance_b)| distance_a.total_cmp(distance_b))
        .map(|(entity, _)| entity)
}

// ── Field tracking ─────────────────────────────────────────────────────────────────────

fn field_tracking_system(
    mut commands: Commands,
    force_field_grid: Res<ForceFieldGrid>,
    mut fields_affected: Query<(Entity, Ref<GridCoords>, &mut FieldAffected)>,
    mut last_grid_version: Local<GridVersion>,
) {
    let grid_changed = force_field_grid.version != *last_grid_version;
    *last_grid_version = force_field_grid.version;

    for (entity, coords, mut affected) in fields_affected.iter_mut() {
        // When the grid is unchanged, only entities that moved cells need re-evaluation.
        // When the grid changed, every entity may now be owned by a different field.
        if !grid_changed && !coords.is_changed() { continue; }

        if !coords.is_in_bounds(force_field_grid.bounds()) { continue; }
        let new_field = force_field_grid[*coords];
        if new_field == affected.current_field { continue; }

        if let Some(old_field) = affected.current_field {
            commands.trigger(ForceFieldExited { field: old_field, target: entity });
        }
        if let Some(new_field) = new_field {
            commands.trigger(ForceFieldEntered { field: new_field, target: entity, exited_field: affected.current_field });
        }
        affected.current_field = new_field;
    }
}

