// Code generated by `#[log_tags]` names this crate as `::logging`.
#[cfg(test)]
extern crate self as logging;

mod macros;
mod system;

pub use lib_derive::log_tags;
pub use system::{Audience, Log, LogBuffer, LogEntryData, LogLevel, LogMessage, LoggingPlugin, Tag, TagSet};

/// What every logging function needs: `Log`, `Tag`, `#[log_tags]` and the `!` forms.
/// Specialized types are imported from the crate root by the consumers that need them.
pub mod prelude {
    pub use crate::system::{Log, Tag};
    pub use crate::log_tags;
    pub use crate::{debug_dev, debug_player, error_dev, error_player, info_dev, info_player, warn_dev, warn_player};
}
