[package]
name = "lib-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.*", default-features = false, features = ["dynamic_linking", "2d"] }
crossbeam-channel = "0.5.*"
nanorand = { version = "0.7.*", features = ["tls"] }
refinery = { version = "0.9.*", features = ["rusqlite"]}
rusqlite = { version = "0.37.*", features = ["bundled"] }
serde = "1.0.*"
strum = { version = "0.28.*", features = ["derive"] }

[dependencies.lib-derive]
path = "../lib-derive"

