[package]
name = "game_core_internal"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
game_core = { workspace = true }
grids = { workspace = true }
alteration = { workspace = true }
persistence = { workspace = true }
states = { workspace = true }

[lints]
workspace = true
